In [14]:
x1=[3,4,-1]+[2,-2,5]
x2=[5,2,4]
y1=np.array([3,4,-1])+np.array([2,-2,5])
y2=np.array([5,2,4])
print(x1,x2,y1,y2)

[3, 4, -1, 2, -2, 5] [5, 2, 4] [5 2 4] [5 2 4]


In [2]:
import numpy as np

In [7]:
import numpy as np
a = np.array(np.arange(8))
b = a.reshape(2,4)
b[0,0] = 100
c = b.flatten()
c[0] = 10
print (a[0])

100


In [10]:
myArray = np.zeros(4)
print(myArray)

[0. 0. 0. 0.]


In [12]:
arr = np.array([[5,-2,3,0],[1,0,-3,4],[-7,4,9,2]])
arr.shape[0]

3

In [21]:
A=[[0,1],[-2,-3]]
print(A)

[[0, 1], [-2, -3]]


In [22]:
np.linalg.eigvals(A)

array([-1., -2.])

In [23]:
import numpy.linalg as LA
LA.eigvals(A)

array([-1., -2.])

In [24]:
from numpy.linalg import eigvals
eigvals(A)

array([-1., -2.])

In [25]:
import numpy
numpy.linalg.eigvals(A)

array([-1., -2.])

In [26]:
np.linalg.eigvals(A)

array([-1., -2.])

In [27]:
from numpy import eigvals
eigvals(A)

ImportError: cannot import name 'eigvals' from 'numpy' (C:\Users\nhing\anaconda3\lib\site-packages\numpy\__init__.py)

In [28]:
import numpy as np
eigvals(A)

array([-1., -2.])

In [29]:
eigvals(A)

array([-1., -2.])

In [30]:
np.linalg.eigvals(A)

array([-1., -2.])